In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [3]:
print(np.append(a,6))

[1 2 3 4 5 6]


In [4]:
b = np.array([[1,2,3],[4,5,6]])

In [5]:
print(np.append(b,7))  #in 2d too, it will add after converting the data in 1d/

[1 2 3 4 5 6 7]


In [6]:
print(np.append(b,[8,9]))

[1 2 3 4 5 6 8 9]


In [7]:
#inserting instead of appending
c= np.array([11,22,33,44,55])# structure-> arrayname,index,value

In [8]:
np.insert(c,1,50)   #inserts value'50' in index 1 of array 'c'
# structure-> arrayname,index,value

array([11, 50, 22, 33, 44, 55])

In [9]:
np.insert(c,1,[50,60])

array([11, 50, 60, 22, 33, 44, 55])

In [10]:
#inserting elements in 2D array
arr = np.array([[1, 2, 3],[4, 5, 6]])
new_row = [40,50,60]
np.insert(arr,0,new_row,0) #structure =>np.insert(arr, placeto insert, value to insert, axis=None)


array([[40, 50, 60],
       [ 1,  2,  3],
       [ 4,  5,  6]])

In [11]:
arr = np.array([[1, 2, 3],[4, 5, 6]])
new_column = [40,50]
np.insert(arr,2,new_column,1)

array([[ 1,  2, 40,  3],
       [ 4,  5, 50,  6]])

In [12]:
arr = np.array([1,2,3,4,5])
print(np.delete(arr,1)) #deletes and prints element at 1 index, ie  2

[1 3 4 5]


In [13]:
arr= np.array([[1,2,3],[4,5,6]])


In [14]:
print(np.delete(arr,0,0))

[[4 5 6]]


In [15]:
print(np.delete(arr,1,0))

[[1 2 3]]


In [16]:
arr= np.array([[1,2,3],[4,5,6],[7,8,9]])
result = np.delete(arr,[0,2],axis=0)
print(result)

[[4 5 6]]
