In [1]:
import numpy as np

In [2]:
a= np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [3]:
print(np.sum(a))

150


In [4]:
print(np.min(a))

10


In [5]:
print(np.max(a))

50


In [6]:
print(np.size(a))

5


In [8]:
print(np.mean(a))

30.0


In [11]:
print(np.cumsum(a)) #cumulative sum

[ 10  30  60 100 150]


In [12]:
print(np.cumprod(a)) #cumulative product

[      10      200     6000   240000 12000000]


In [13]:
a= [10, 20, 30, 40, 50]
b=[5, 15, 25, 35, 45]
price = np.array(a)
quantity =np.array(b)
print(price,"\n", quantity)

[10 20 30 40 50] 
 [ 5 15 25 35 45]


In [32]:
totalofpriceandproduct = np.cumprod([price,quantity],axis=0)
print(totalofpriceandproduct) 
#this gives the total for a price for quantity

[[  10   20   30   40   50]
 [  50  300  750 1400 2250]]


In [41]:
c =totalofpriceandproduct
print(c[1].sum())



4750
