In [1]:
import numpy as np

In [2]:
a = [20,30,40,50,60]
arr= np.array(a)
print(arr)

[20 30 40 50 60]


In [3]:
print(arr.shape) #gives the number of elements

(5,)


In [4]:
print(len(arr)) #length 

5


In [5]:
print(np.size(arr)) #Gives the size

5


In [6]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
print(arr.dtype)

int32


In [8]:
print(arr.astype(float))  #conversion into float


[20. 30. 40. 50. 60.]


In [9]:
b= [[1,2,3,4,5], [6,7,8,9,10]]
newarr= np.array(b)
print(b)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [10]:
print(newarr.shape)

(2, 5)


In [11]:
print(len(newarr))

2


In [12]:
print(np.size(newarr))

10


In [13]:
print(type(newarr))

<class 'numpy.ndarray'>


In [14]:
print((newarr.dtype))

int32


In [15]:
print(newarr.astype(float)) #coonverts the values into float.

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
