In [1]:
import numpy as np

In [2]:
a = np.array([12,13,15,16])
b= np.array([25,26,62,12])
print(a+b)

[37 39 77 28]


In [3]:
#concatenate(combine two array)
arr1 = np.array([12,13,15,16])
arr2= np.array([25,26,62,12])
print(np.concatenate([arr1,arr2]))


[12 13 15 16 25 26 62 12]


In [4]:
print(np.concatenate([arr1,arr2],axis= 0)) #for a single 1D.

[12 13 15 16 25 26 62 12]


In [5]:
arr1 = np.array([[12,13],[15,16]])
arr2= np.array([[25,26],[62,12]])

In [6]:
print(np.concatenate([arr1,arr2],axis= 1)) #for  2d

[[12 13 25 26]
 [15 16 62 12]]


In [7]:
print(np.hstack([arr1,arr2])) #hstack is horizontalstak, 
#concatenating in horizontal way

[[12 13 25 26]
 [15 16 62 12]]


In [8]:
print(np.vstack([arr1,arr2])) #vstack is vertcial stack,
#concatenating in vertical way

[[12 13]
 [15 16]
 [25 26]
 [62 12]]


In [9]:
a = np.array([1,2,3,4,5])

In [10]:
print(np.array(a))

[1 2 3 4 5]


In [11]:
b=(np.array_split(a,3)) #splits array "a" 
#into 3 seperate arrays are store in b,
#print b
print(b)
print(b[1])

[array([1, 2]), array([3, 4]), array([5])]
[3 4]


In [12]:
a = np.array([[1,2,3],[4,5,6]]) #if 2 array then,  also same way of splitting

In [13]:
print(np.array_split(a,2))

[array([[1, 2, 3]]), array([[4, 5, 6]])]
