In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5]) #array creations,1D

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
print(arr) #printing array

[1 2 3 4 5]


In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.size #knowing  the array size

5

In [7]:
arr.shape #array shape

(5,)

In [8]:
arr[0:3] #slicing in array ,starts from 0 till 2, doesnt count till 3.

array([1, 2, 3])

In [9]:
print(arr[0:3]) #printing the sliced elemenets

[1 2 3]


In [10]:
arr[0:]

array([1, 2, 3, 4, 5])

In [11]:
arr[:2]

array([1, 2])

In [12]:
print(arr[0:3])

[1 2 3]


In [13]:
print(arr[2:])

[3 4 5]


In [14]:
print(arr[3:5])

[4 5]


In [15]:
newarr = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]]) 
#creation of 2d arryas

In [16]:
print(newarr) #printing the 2d arrays

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
newarr[0,1] #zeroth row, 2nd column 
#indexing  starts from 0
#finding elements in 2d array

2

In [18]:
newarr[1,1] #first row, first column #indexing  starts from 0

7

In [19]:
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [20]:
#slicing in 2d array
#newarr[row_start:row_end, col_start:col_end]

print(newarr[0:2,0:2])  #counts from 0 to 1, doesnt count till 2, so 0 and  1.
#0:2 for rows: ie 
#Row 0: [1, 2, 3, 4, 5]
#Row 1: [6, 7, 8, 9, 10]
#and
#0:2 for columns: ie
#Column 0: [1, 6, 11]
#Column 1: [2, 7, 12]

[[1 2]
 [6 7]]


In [21]:
print(newarr[0:2,0:3])  #row from 0 to 2, means 0 and 1
#ieRow 0: [1, 2, 3, 4, 5]
#Row 1: [6, 7, 8, 9, 10]
#and column from 0 to3, means 0,1,2
#Column 0: [1, 6, 11]
#Column 1: [2, 7, 12]
#Column 2: [3, 8, 13]
#ie, for rows O and 1, it counts 3 columns.

[[1 2 3]
 [6 7 8]]


In [22]:
print(newarr[0:2,0:2]) #its better to use 0:2 and 0:2 for both rows 
#and columns,
#if wanted 3elements use 0:3 for both"

[[1 2]
 [6 7]]


In [23]:
print(newarr[0:3,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [24]:
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [25]:
#suppose if i want  to slice 2 and 3 from first row,
print(newarr[0,1:3]) #for 0th row, slice from  1 to 3, ie 2 & 3 
#here 1 is 0th column, 2 is 1st and 3 is 2nd as, indexing starts from 0

[2 3]


In [26]:
print(newarr[1,2:4]) #2nd row, slice from 2nd column till 4th column, ie 2,3 column, ie  ans 8,9
#indexing starts from 0.

[8 9]


In [27]:
print(newarr[2,2:4])

[13 14]


#attributets of array

In [28]:
numbers= np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15]])

In [29]:
print(numbers)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [30]:
numbers.size

15

In [31]:
numbers.shape 

(3, 5)

In [32]:
numbers.ndim #numbers of dimenions ,ie rows are first dimension  and columns are 2nd dimension

2

In [33]:
print(numbers.dtype)

int32
