In [1]:
import numpy as np

In [2]:
myarray = np.array([1,2,3,4,5]) #creating a array in numpy

In [3]:
myarray

array([1, 2, 3, 4, 5])

In [4]:
myarray = np.array([1,2,3,4,], np.int8)  #integer will be of 8 bit.

In [5]:
myarray

array([1, 2, 3, 4], dtype=int8)

In [6]:
myarray[0]#accesing first element in list

1

In [7]:
myarray[1]#accesing second element in list

2

In [8]:
myarray[3] #accessing 4th element in list

4

In [9]:
myarray = np.array([[1,2,3,4,5]]) #In    2d aray,here 1 row, 5column

In [10]:
myarray[0]

array([1, 2, 3, 4, 5])

In [11]:
myarray[0,1]
#0: The row index, which refers to the first (and only) row.
#1: The column index, which refers to the second column (indexing starts at 0).

2

In [12]:
myarray[0,0]

1

In [13]:
myarray[0,3]

4

In [14]:
myarray[0,4]

5

In [15]:
myarray.shape #gives the shape, 1 row, and 5 columns

(1, 5)

In [16]:
myarray.dtype  #gives the type of integer

dtype('int32')

In [20]:
myarray[0,1]  

2

In [23]:
myarray[0,1] = 33 #changing element in 2d array

In [22]:
myarray

array([[ 1, 33,  3,  4,  5]])