In [1]:
import numpy as np

In [3]:
#creating arrays in numpy 

#Array creation : conversion from otherpython structures, list, tuples


In [6]:
#creating a 2d numpyarray using list
listarray =  np.array([[1,2,3] , [5,6,7],[8,9,10]])

In [7]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
listarray.dtype

dtype('int32')

In [9]:
listarray.shape

(3, 3)

In [10]:
listarray.size

9

In [14]:
listarray[2,2] = 12

In [15]:
listarray

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 8,  9, 12]])

In [16]:
np.array ({34,33,55}) # create a NumPy array from a set

array({33, 34, 55}, dtype=object)

#Inrinsic numpy array creation objects

In [17]:
zeros =   np.zeros((2,5)) #gives an 2 by 5 arrays with all eements zeros

In [18]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros.shape

(2, 5)

In [21]:
range =  np.arange(15)  #gives an  numpy array from 0 to 14

In [24]:
range 
#Function: np.arange(start, stop, step, dtype)
#generates an array of evenly spaced values within a specified range.
#np.arange() is similar to Python's built-in range(), 
#but it returns a NumPy array instead of a Python range object.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
lspace = np.linspace(1,50,10)
#np.linspace(start, stop, num))
#Generates an array of num evenly spaced values between the start and stop values
# It generates an array of 10  evenly spaced values between a start value 1 and stop value 50.

In [33]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [37]:
lspace= np.linspace(1,5,4)

In [38]:
lspace = np.linspace(1,4,4)

In [39]:
lspace

array([1., 2., 3., 4.])

In [42]:
empty = np.empty((4,6)) 
#gives a 2d array of 4 by 6, ie 4 rows, 6 columns, with garbage value or random vlaue  
#alreaady present in memory location

In [43]:
empty

array([[4.67296746e-307, 1.69121096e-306, 1.42418987e-306,
        7.56587584e-307, 1.37961302e-306, 1.05699242e-307],
       [8.01097889e-307, 1.78020169e-306, 7.56601165e-307,
        1.02359984e-306, 1.33510679e-306, 2.22522597e-306],
       [1.78019761e-306, 1.37962185e-306, 1.78019625e-306,
        6.89812281e-307, 9.34609790e-307, 1.24610723e-306],
       [1.05700515e-307, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 8.90095411e-307]])

In [44]:
empty_like= np.empty_like(lspace) #copies of the size of old arrays and creaets an empty array

In [46]:
empty_like  #copies teh

array([1., 2., 3., 4.])

In [47]:
identity = np.identity(45) 
#create an identity matrix of 45  by  45 size

In [48]:
identity

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [49]:
identity.shape

(45, 45)

In [50]:
identity.size

2025

In [51]:
newarray =  np.arange(99)

In [52]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [53]:
#if i need to reshape

In [56]:
newarray.reshape(3,33) # creates a new array with 3 rows and 33 columns
#the numbers 3 and 33  should be the size of 99,  orelse it won't work 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
newarray.reshape(3,31) #gives error, beacuse 3*31 is 93, but our original array size was 99.


ValueError: cannot reshape array of size 99 into shape (3,31)

In [58]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
newarray  #hasnt change, newarray.reshape(3,31) gives error, need to perform again,to applychagnes

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [65]:
newarray = newarray.reshape(3,33)

In [67]:
newarray #gives the updated array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [74]:
newarray  =newarray.ravel() #flatten a multi-dimensional array into a 1D array

In [75]:
newarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [73]:
newarray.shape

(99,)

#AXIS IN NUMPY