In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
       [4,5,6],
       [7,8,9]]
)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
sum_axis0= np.sum(arr,axis=0) #ie,  1+4+7 =12, 2+5+8=15, 3+6+9=18 , =>12,15,18
print(sum_axis0)
#axis 0, vertical add rows, downwards

[12 15 18]


In [4]:
sum_axis1 = np.sum(arr,axis =1) #ie, 1+2+3 =6,  4+5+6 = 15, 7+8+9 = 24, => 6,15,24
print(sum_axis1)

[ 6 15 24]


In [7]:
#adding a new row or column using axis
current_array = np.array([[10,11,12]])
adding_array = [15,16,17]
result_array = np.vstack([current_array,adding_array])
print(result_array)

[[10 11 12]
 [15 16 17]]


In [20]:
#adding new row, using vstack.
current_array = np.array([[10,11,12] ,[14,55,26],[12,41,22]])
adding_array = [15,16,17]
result_array= np.vstack([current_array,adding_array])
print(result_array)

[[10 11 12]
 [14 55 26]
 [12 41 22]
 [15 16 17]]


In [24]:
#adding new row, using vstack in specific positions.
current_array = np.array([[10,11,12] ,[14,55,26],[12,41,22]])
adding_array = [15,16,17]
result_array= np.vstack([current_array[:1],adding_array,current_array[1:]])
print(result_array)

[[10 11 12]
 [15 16 17]
 [14 55 26]
 [12 41 22]]


In [27]:
#In-Place Modification , without creating a new array
current_array = np.array([[10, 11, 12], [14, 55, 26], [12, 41, 22]])
adding_array=  [33,44,75]
current_array= np.append(current_array,[adding_array],axis=0)
print(current_array)

[[10 11 12]
 [14 55 26]
 [12 41 22]
 [33 44 75]]


In [28]:
#In-Place Modification at specific postion , we use insert, without creating a new array
current_array = np.array([[10, 11, 12], [14, 55, 26], [12, 41, 22]])
adding_array=  [33,44,75]
current_array= np.insert(current_array,1,adding_array,axis=0)
print(current_array)

[[10 11 12]
 [33 44 75]
 [14 55 26]
 [12 41 22]]
