In [1]:
import numpy as np

In [2]:
arr1 = np.array([12,23,24,55,67])
arr2 =np.array([14,15,16,17,77])

In [3]:
print(arr1+arr2)

[ 26  38  40  72 144]


In [4]:
print(np.add(arr1,arr2))

[ 26  38  40  72 144]


In [5]:
arr3 = np.array([[22,25],[26,17]])
arr4 = np.array([[24,26],[56,67]])

In [6]:
print(arr3+arr4)

[[46 51]
 [82 84]]


In [7]:
arr5 = np.array([12,23,24,55,67])
arr6 =np.array([14,15,16,17,77])

In [8]:
print(arr1-arr2)

[ -2   8   8  38 -10]


In [9]:
print(np.subtract(arr5,arr6))

[ -2   8   8  38 -10]


In [10]:
arr7 = np.array([[22,25],[26,17]])
arr8 = np.array([[24,26],[56,67]])

In [11]:
print(arr7*arr8)

[[ 528  650]
 [1456 1139]]


In [12]:
print(np.multiply(arr7,arr8))

[[ 528  650]
 [1456 1139]]


In [13]:
print(arr7/arr8)

[[0.91666667 0.96153846]
 [0.46428571 0.25373134]]


In [14]:
print(np.divide(arr7,arr8))

[[0.91666667 0.96153846]
 [0.46428571 0.25373134]]


In [15]:
arr9 = np.array([22,25,26,17])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 144  529  576 3025 4489]


In [16]:
arr10 =  np.array([ 144 , 529,  576 ,3025 ,4489])
print(np.sqrt(arr10))

[12. 23. 24. 55. 67.]
