In [1]:
import numpy as np

In [2]:
arr = np.array([17,55,21,12,14,88,33,46,66]) #create an unsorted array.
print(arr)

[17 55 21 12 14 88 33 46 66]


In [3]:
sorted_arr = np.sort(arr)  #sorting the array
print(sorted_arr)

[12 14 17 21 33 46 55 66 88]


In [4]:
arr = np.array([[17,55,21,12],[14,88,33,46]])#create an  2d unsorted array.
print(arr)

[[17 55 21 12]
 [14 88 33 46]]


In [5]:
sorted_arr = np.sort(arr)
print(sorted_arr)

[[12 17 21 55]
 [14 33 46 88]]


In [6]:
arr = np.array([17,55,21,12,14,88,33,46,66])
searched_value = np.where(arr == 21)
print(searched_value)


(array([2], dtype=int64),)


In [7]:
searched_values = np.where(arr%2== 0)#gives indexs of all number divisible by 2
print(searched_values)

(array([3, 4, 5, 7, 8], dtype=int64),)


In [8]:
#SEARCH SORTED,  array needs to be sorted , 
#gives the index of where the element is placed in the array.
arr = np.array([12 ,14, 17, 21, 33, 46, 55, 66, 88])
search_sorted = np.searchsorted(arr,33)
print(search_sorted)

4


In [9]:
arr = np.array([12 ,14, 17, 21, 33, 46, 55, 66, 88])
filtered_array = arr[arr>=17] #filter elements  greater than 17
print(filtered_array)

[17 21 33 46 55 66 88]


In [10]:
#if i want to fidn index
arr = np.array([12, 14, 17, 21, 33, 46, 55, 66, 88])
indices = np.where(arr> 17)
print(indices)
filtered_array = arr[indices]
print(filtered_array)

(array([3, 4, 5, 6, 7, 8], dtype=int64),)
[21 33 46 55 66 88]


In [11]:
#
arr = np.array([12, 14, 17, 21, 33, 46, 55, 66, 88])
filtered_array=  arr[(arr>=20) & (arr<=80)]
print(filtered_array)

[21 33 46 55 66]
